apiVersion: v1
kind: Service
metadata:
  name: cafesite-service
spec:
  type: NodePort
  selector:
    app: cafesite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32100
